services:
  api-teste:
    container_name: api-teste
    hostname: api-teste
    image: python:3.12-slim
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    working_dir: /src
    command: >
      sh -c "pip install -U pip && pip install fastapi==0.115.5 uvicorn==0.32.0 && uvicorn app:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: curl -f http://localhost:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s